/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppStoryRouteImport } from './routes/_app.story'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppExplorerRouteImport } from './routes/_app.explorer'
import { Route as AppEdaRouteImport } from './routes/_app.eda'
import { Route as AppDetectiveRouteImport } from './routes/_app.detective'
import { Route as AppDatasetRouteImport } from './routes/_app.dataset'
import { Route as AppCleaningRouteImport } from './routes/_app.cleaning'
import { Route as AppChatRouteImport } from './routes/_app.chat'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppStoryRoute = AppStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorerRoute = AppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AppRoute,
} as any)
const AppEdaRoute = AppEdaRouteImport.update({
  id: '/eda',
  path: '/eda',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectiveRoute = AppDetectiveRouteImport.update({
  id: '/detective',
  path: '/detective',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetRoute = AppDatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => AppRoute,
} as any)
const AppCleaningRoute = AppCleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/chat': typeof AppChatRoute
  '/cleaning': typeof AppCleaningRoute
  '/dataset': typeof AppDatasetRoute
  '/detective': typeof AppDetectiveRoute
  '/eda': typeof AppEdaRoute
  '/explorer': typeof AppExplorerRoute
  '/history': typeof AppHistoryRoute
  '/insights': typeof AppInsightsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/story': typeof AppStoryRoute
  '/team': typeof AppTeamRoute
  '/upload': typeof AppUploadRoute
}
export interface FileRoutesByTo {
  '/chat': typeof AppChatRoute
  '/cleaning': typeof AppCleaningRoute
  '/dataset': typeof AppDatasetRoute
  '/detective': typeof AppDetectiveRoute
  '/eda': typeof AppEdaRoute
  '/explorer': typeof AppExplorerRoute
  '/history': typeof AppHistoryRoute
  '/insights': typeof AppInsightsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/story': typeof AppStoryRoute
  '/team': typeof AppTeamRoute
  '/upload': typeof AppUploadRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/cleaning': typeof AppCleaningRoute
  '/_app/dataset': typeof AppDatasetRoute
  '/_app/detective': typeof AppDetectiveRoute
  '/_app/eda': typeof AppEdaRoute
  '/_app/explorer': typeof AppExplorerRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/story': typeof AppStoryRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/cleaning'
    | '/dataset'
    | '/detective'
    | '/eda'
    | '/explorer'
    | '/history'
    | '/insights'
    | '/reports'
    | '/settings'
    | '/story'
    | '/team'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/cleaning'
    | '/dataset'
    | '/detective'
    | '/eda'
    | '/explorer'
    | '/history'
    | '/insights'
    | '/reports'
    | '/settings'
    | '/story'
    | '/team'
    | '/upload'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/chat'
    | '/_app/cleaning'
    | '/_app/dataset'
    | '/_app/detective'
    | '/_app/eda'
    | '/_app/explorer'
    | '/_app/history'
    | '/_app/insights'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/story'
    | '/_app/team'
    | '/_app/upload'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/story': {
      id: '/_app/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof AppStoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorer': {
      id: '/_app/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AppExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eda': {
      id: '/_app/eda'
      path: '/eda'
      fullPath: '/eda'
      preLoaderRoute: typeof AppEdaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detective': {
      id: '/_app/detective'
      path: '/detective'
      fullPath: '/detective'
      preLoaderRoute: typeof AppDetectiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dataset': {
      id: '/_app/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof AppDatasetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cleaning': {
      id: '/_app/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof AppCleaningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppCleaningRoute: typeof AppCleaningRoute
  AppDatasetRoute: typeof AppDatasetRoute
  AppDetectiveRoute: typeof AppDetectiveRoute
  AppEdaRoute: typeof AppEdaRoute
  AppExplorerRoute: typeof AppExplorerRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStoryRoute: typeof AppStoryRoute
  AppTeamRoute: typeof AppTeamRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppCleaningRoute: AppCleaningRoute,
  AppDatasetRoute: AppDatasetRoute,
  AppDetectiveRoute: AppDetectiveRoute,
  AppEdaRoute: AppEdaRoute,
  AppExplorerRoute: AppExplorerRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStoryRoute: AppStoryRoute,
  AppTeamRoute: AppTeamRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
